#!/usr/bin/env ruby

STDOUT.sync = true

require 'json'
require 'base64'
require 'fileutils'

username = ENV['QUERY_STRING'].split('=').last

Thread.new do
  loop do
    fs_event_data = JSON.parse(STDIN.readline)
    project_path = fs_event_data['project']['path']
    file_path    = fs_event_data['file']['path']
    #full_path    = "/Users/loganhasson/Desktop/code_dir/#{(file_path.split('/') - project_path.split('/')).join('/')}"
    full_path    = "/home/#{username}/code/#{(file_path.split('/') - project_path.split('/')).join('/')}"

    case fs_event_data['action']
    when 'local_save'
      needed_dirs = full_path.split('/')[0..-2].join('/')
      FileUtils.mkdir_p(needed_dirs)

      File.open(full_path, 'w+') do |f|
        f.write(Base64.decode64(fs_event_data['buffer']['content']))
      end
    when 'local_delete'
      FileUtils.rm_rf(full_path)
    else
      # Nothing
    end
  end
end

while true
end
