#!/usr/bin/env ruby

STDOUT.sync = true

require 'pty'
require 'json'
require 'net/http'
require 'uri'
require 'base64'

token = ENV['QUERY_STRING'].split('token=').last
uri = URI('https://learn.co/api/v1/users/me')
response = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
  #req = Net::HTTP::Get.new(uri)
  req = Net::HTTP::Get.new(uri.request_uri) # This is for jruby to work
  req['Authorization'] = "Bearer #{token}"

  http.request(req)
end

username = JSON.parse(response.body)['username'].sub('hasson', 'test')

stdout, stdin, _pid = PTY.spawn("TERM=xterm-256color sudo su - #{username}")

Thread.new do
  loop do
    line = stdout.readpartial(4096)
    puts Base64.encode64(line)
  end
end

Thread.new do
  loop do
    stdin << STDIN.readline.gsub(/\n{1}$/, '').gsub(/\n{2}$/, "\n")
  end
end

while true
end
