#!/usr/bin/env ruby

STDOUT.sync = true

require 'pty'
username = ENV['QUERY_STRING'].split('=').last

stdout, stdin, _pid = PTY.spawn("sudo su - #{username}")

Thread.new do
  loop do
    puts stdout.readpartial(4096)
  end
end

Thread.new do
  loop do
    stdin << STDIN.readpartial(4096).gsub(/\n{1}/, '').gsub(/\n{2}/, "\n")
  end
end

while true
end
